config/routes.rb
Rails.application.routes.draw do
  get 'date_cleaner/edit'
  get 'cancel_service/cancel'
  patch 'orders/:id', to: 'orders#update', as: :update_order

  root 'home#index'

  devise_for :users 

  resources :the_users
  resources :date_cleaner, only: [:update, :edit]
  resources :clients,      only: [:edit, :update]
  resources :addresses
  resources :orders
  resources :services
  resources :cleaners,     only: [:edit, :update]
  resources :admins,       only: [:edit, :update]
  get '*path' => redirect('/')
end

app/models/service.rb
class Service < ApplicationRecord
    belongs_to :address
    belongs_to :order
    has_one :client, through: :order, dependent: :nullify
    belongs_to :cleaner, optional: true
    validates :address_id, presence: true
    validates :order_id, presence: true
    validates :price, presence: true

    enum status: {cancelado: 0, pendiente: 1, 
        asignado: 2, completado: 3}

    def self.paid
      joins(:order).where(orders: { order_status: 2 } )
    end

    def self.search(status)
      if !status.blank?
          where("status = (?)", status)
        else
          self.all
      end
    end

    def update_status(new_status)
        self.update(status: new_status) 
    end

    def check_status
        #Si no esta cancelado
        if self.status != 0
          #Si no ha vencido
          if self.date > Date.today
            #Y no tiene trabajador
            if self.cleaner_id.nil?
              update_status(1)
            #Si tiene trabajador
            else
              update_status(2)
            end
          #Si vencio
          else
            #Y no tiene trabajador
            if self.cleaner_id.nil?
              update_status(0)
            #Y si tiene trabajador
            else
              update_status(3)
            end
          end
        end
    end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: [:show, :edit, :update]
  before_action :set_addresses, only: [:new, :create]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :authenticate_information
  before_action :correct_user, only:[:show, :edit, :update]
  before_action :change_status_services, only: [:index]
  

  # GET /services
  # GET /services.json
  def index
    name = params[:search_name]
    email = params[:search_email]
    status = params[:search_status]

    if current_user.user_type == "admin"
      @services = Service.all.search(status).order(date: :desc).page(params[:page]).per(30)
    elsif current_user.user_type == "cleaner"
      @services = current_user.cleaners.first.services.order(:date).page(params[:page]).per(30)
    else #if == client
      @services = current_user.clients.first.services.page(params[:page]).per(30) 
    end
  end

  # GET /services/1
  # GET /services/1.json
  def show
    redirect_to services_path
  end

  # GET /services/new
  def new
    if current_user.client?
      @order_id = params[:order_id]
      @dates = params[:dates].split(",")
      @price = @dates.count * 55000    
      @service = Service.new
    else
      redirect_to services_path
    end
  end

  # GET /services/1/edit
  def edit
    if @service.cancelado? || @service.completado? || !current_user.admin?
      redirect_to services_path
    else
      @client = @service.client
      @cleaner = @service.cleaner
      cleaners_object = Cleaner.available_cleaners(@service.date)
      @cleaners = cleaners_object.pluck(:name,:id).to_h
    end
  end

  # POST /services
  # POST /services.json
  def create

    order_id = params[:order_id].to_i
    num_dates = params[:num_dates].to_i
    
    dates = (0...num_dates).map {|date| params["date_#{date}"]}
    only_addresses = (0...num_dates).map {|address| params["address_#{address}"]}
    addresses_ids = only_addresses.map {|address| @addresses[address]}
    
    new_service = dates.zip(addresses_ids).to_h

    new_service.each do |date,address|
      date = Date.strptime(date,'%m/%d/%Y')
      @service = Service.create!(date: date, price: 55000, address_id: address, order_id: order_id)

        if !@service.save
          redirect_to new_service_path, notice: 'Ha ocurrido un error'
        end

    end
    UserMailer.orders(@service.order).deliver_now
    redirect_to orders_path, notice: 'Sus servicios han sido solicitados exitosamente, por favor revise su correo para ver la factura'
  end


  def update
    date = params[:service][:date]
    cleaner_id = params[:cleaner_id]
      if @service.update(date: date, cleaner_id: cleaner_id)
          @service.check_status
        redirect_to order_path(@service.order.id), notice: 'Servicio actualizado.'
      else
        redirect_to services_path, notice: 'error.'
      end
  end


  def destroy
    @service.destroy
    respond_to do |format|
      format.html { redirect_to services_url, notice: 'Service was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service
      @service = Service.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    #def service_params
    #  params.require(:service).permit(:date, :status, :address_id, :order_id, :cleaner_id, :price)
    #end

    def set_addresses
      @addresses = current_user.addresses.pluck(:body,:id).to_h
    end

    def correct_user
      unless current_user.user_type == "admin" || 
              current_user.id == @service.order.client.user.id
        flash[:alert] = "Contenido no disponible"
        redirect_to services_path
      end
    end

    def change_status_services
      services = Service.where("date <= ?", Date.today).where(status: ["asignado", "pendiente"])
        services.each do |service|
          if service.status == "asignado" && service.date < Date.today
            service.update(status: 3.to_i) 
          elsif service.status == "pendiente" && service.date <= Date.today
            service.update(status: 0.to_i)
          end
        end
    end

end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/services/_admin.html.erb
<div style="width:500px"><%= paginate @services %></div>            
 <br> 
 
 <table class="table is-narrow is-hoverable -row-hover-background-color primary">
   <thead>
     <tr>
      <th>Fecha del servicio</th>
      <th>Cliente</th>
      <th>Email</th>
      <th>Telefono</th>
      <th>Direccion</th>
      <th>Estado</th>
      <th>Trabajadora</th>
      <th>Accion</th>
     </tr>
   </thead>

  <tbody>
    <% @services.each do |service| %>
      <tr>
        <td><%= service.date %></td>
        <% if service.client.nil?%> 
          <td>eliminado</td>
          <td>eliminado</td>
          <td>eliminado</td>
        <%else%>
          <td><%= service.client.name %></td>
          <td><%= service.client.user.email %></td>
          <td><%= service.client.phone %></td>
        <%end%>
        <td><%= service.address.body %></td>
        <td><%= service.status %></td>
        <% if service.cleaner.nil? && service.status == "pendiente" %>
          <td>por asignar</td>
        <% elsif service.cleaner.nil? && service.status == "cancelado" %>
         <td></td>
        <% else %>
         <td><%= service.cleaner.name %></td>
        <%end%>
          <td><% if service.asignado? || service.pendiente?  %>
            <%= link_to 'Asignar', edit_service_path(service), class: "button is-small" %>
            <%if service.order.pagado?%>
              <%= link_to 'Cancelar', cancel_service_cancel_path(service), 
                  data: { confirm: 'Seguro desea cancelar este servicio?' }, class: "button is-small" %>
            <% end %>
          <% end %>
          </td>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/services/_cleaner.html.erb
<div style="width:500px"><%= paginate @services %></div>            
 <br> 
 
 <table class="table is-narrow is-hoverable -row-hover-background-color primary">
   <thead>
     <tr>
      <th>Fecha de servicio</th>
      <th>Cliente</th>
      <th>Email</th>
      <th>Telefono</th>
      <th>Direccion</th>
      <th>Estado</th>
     </tr>
   </thead>

  <tbody>
    <% @services.each do |service| %>
      <tr>
        <td><%= service.date %></td>
        <% if service.client.nil?%> 
          <td>eliminado</td>
          <td>eliminado</td>
          <td>eliminado</td>
        <%else%>
          <td><%= service.client.name %></td>
          <td><%= service.client.user.email %></td>
          <td><%= service.client.phone %></td>
        <%end%>
        <td><%= service.address.body %></td>
        <td><%= service.status %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/services/_client.html.erb
<div style="width:500px"><%= paginate @services %></div>            
 <br> 
 
 <table class="table is-narrow is-hoverable -row-hover-background-color primary">
   <thead>
     <tr>
      <th>Fecha de servicio</th>
      <th>Direccion</th>
      <th>Estado</th>
      <th>Trabajadora</th>
      <th>Accion</th>
     </tr>
   </thead>

  <tbody>
    <% @services.each do |service| %>
      <tr>
        <td><%= service.date %></td>
        <td><%= service.address.body %></td>
        <td><%= service.status %></td>
        <td><% if service.cleaner.nil?%>
            Por asignar 
          <% else %>
            <%= service.cleaner.name %>
          <% end %>
        </td>
        <td>
          <% if service.status == "pendiente" || service.status == "asignado" %>
            <%= link_to 'Cancelar', cancel_service_cancel_path(service), 
            data: { confirm: 'Seguro desea cancelar este servicio?' }, class: "button is-small" %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/services/_form.html.erb
 <table>
  <thead>
    <tr>
      <th>Fecha</th>
      <th>Dirección</th>
    </tr>
  </thead>
    <%= simple_form_for(@service) do |f| %>

    <div class="form-inputs">
      <div><strong>Defina los servicios</strong></div>
      <tbody>
        <% @dates.each_with_index do |date, i| %>
          <tr>
            <td> <input name = "date_<%= "#{i}" %>" value = <%= date %>></input></td>
            
            <td>
              <div class="field">
               <div class="control">
                    <%= select_tag "address_#{i}", options_for_select(@addresses.keys)%>
                </div>
              </div>
            </td>


            <td><%= hidden_field_tag :price,@price%></td>
            <td><%= hidden_field_tag :order_id,@order_id%></td>
            <td><%= hidden_field_tag :num_dates,i+1%></td>

          </tr>
        <% end %>
      </tbody>
  </table>
  <br>
  <p>El valor total de sus servicios es de <strong> <%= number_to_currency(@price)%> <strong>
 <br>
 <br>
   <div class="form-actions">
     <%= f.button :submit, class:"button is-info is-medium"  %>
   </div>
   <br>
   <br>
 <% end %>

app/views/services/edit.html.erb
<% provide(:title, "Edicion de servicio") %>
<% provide(:title_header, "Edicion de servicio") %>

<%= render 'shared/header_dinamic' %>

<div class="section">                                                           
  <div class="container" align="center">                                        
    <div class="columns is-centered">                                           
      <div class="column is-6"> 
        <%= form_for(@service) do |f| %>   
          <table>
          <thead></thead>
          <tbody>
          
          <tr><td> Estado:</td> <td> <%= @service.status %> </td></tr>
          <tr><td> Fecha de servicio: </td>
            <td> <div class="field">
                <div class="control">
                  <%= f.text_field :date,
                  type: :date, 
                              required: true, 
                              input_html: { class: "input"}, 
                              wrapper: false, 
                              label_html: { class: "label" } %>
                </div>
              </div>
            </td>
          </tr>
          </div>
          <tr> <td>Cliente: </td><td> <%= @service.client.name %> </td></tr>
          <tr> <td>Telefono: </td><td> <%= @service.client.phone %> </td></tr>
          <tr> <td>Dirección: </td><td> <%= @service.address.body %> </td></tr>
          <tr> <td>Profesional de limpieza</td>
          <% if @service.cleaner.nil? %>
            <td><%= select_tag :cleaner_id ,options_for_select(@cleaners.each{|k,v| [k,v]}), prompt: "seleccione profesional"%></td>
          <%else%>
            <td><%= select_tag :cleaner_id ,options_for_select(@cleaners.each{|k,v| [k,v]}), prompt: @service.cleaner.name %></td>
          <%end%>
          </tr>
         <tbody>
        </table>
        <br>
          <div class="actions">
            <%= f.submit "Asignar", class:"button is-info" %>
          </div>
        <% end %>
        <br>
        <%= link_to 'Regresar', :back, class: "button" %>
      </div>
    </div>
  </div>
</div>

app/views/services/index.html.erb
<% provide(:title, "Servicios") %>
<% provide(:title_header, "Servicios") %>

<%= render 'shared/header_dinamic' %>

<div class="hero-body">                                                         
  <div class="container" align="center">                                        
    <div class="table-container" style="width: 1100px; ">

      <div class="container" style="padding-left:120px">
        <% unless current_user.cleaner? %>
          <%= form_tag(services_path, method: :get) do %>
            <div style = "width:200px; float:left">
            <%= select_tag :search_status ,options_for_select(Service.statuses), prompt: "Select status" %></div>
            <%= submit_tag ("Buscar"), class: 'button is-link is-small'%>
          <% end %>
          <br>
        <% end %>
      </div>
                                                                             
      <%= render 'services/admin' if current_user.user_type == 'admin'%>
      <%= render 'services/client' if current_user.user_type == 'client'%>
      <%= render 'services/cleaner' if current_user.user_type == 'cleaner'%>
      <br>
      <% if current_user.client?%>
        <%= link_to 'Ordenar servicios', new_order_path, class: "button is-info is-rounded" unless current_user.cleaner?%>
      <% end %>
      <br>
      <br>
       <%= link_to 'Regresar', root_path,class:"button"%>
    </div>
  </div>
</div>

app/views/services/new.html.erb
<% provide(:title, "Ordenar servicios") %>
<% provide(:title_header, "Ordenar servicios") %>

<%= render 'shared/header_dinamic' %><br>

<section class="section">                                                       
  <div class="container">                                                       
    <div class="columns is-centered">                                           
      <div class="column is-4">
        <%= render 'form', service: @service %>
        <%= link_to 'Regresar', new_order_path, class: "button" %>
      </div>
    </div>
  </div>
</section>

app/views/services/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fecha:</strong>
  <%= @service.date %>
</p>

<p>
  <strong>Estado:</strong>
  <%= @service.status %>
</p>

<p>
  <strong>Direccion:</strong>
  <%= @service.address.body %>
</p>

<p>
  <strong>Cliente:</strong>
  <%= @service.location.client.name %>
</p>

<p>
  <strong>Trabajadora:</strong>
  <%= @service.cleaner.name %>
</p>

<p>
  <strong>Precio:</strong>
  <%= @service.price %>
</p>

<%= link_to 'Editar', edit_service_path(@service) %> |
<%= link_to 'Regresar', services_path %> |
<%= link_to 'Cancelar', cancel_service_cancel_path(@service), data: { confirm: 'Seguro desea cancelar este servicio?' } %>