config/routes.rb
Rails.application.routes.draw do
  get 'date_cleaner/edit'
  get 'cancel_service/cancel'
  patch 'orders/:id', to: 'orders#update', as: :update_order

  root 'home#index'

  devise_for :users 

  resources :the_users
  resources :date_cleaner, only: [:update, :edit]
  resources :clients,      only: [:edit, :update]
  resources :addresses
  resources :orders
  resources :services
  resources :cleaners,     only: [:edit, :update]
  resources :admins,       only: [:edit, :update]
  get '*path' => redirect('/')
end

app/controllers/the_users_controller.rb
class TheUsersController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]
  before_action :authenticate_information
  before_action :user_admin
  
  def index
    email = params[:search_email]
    @the_users = User.where('user_type != (?)',0).search(email).page(params[:page]).per(10)
    # @the_users = User.all.search(email).page(params[:page]).per(10)
  end

  def new
    @the_user = User.new
  end

  def edit
    @the_user = User.find(params[:id])
  end

  def update
    @the_user = User.find(params[:id])

    user_type = @the_user.user_type
    user_type_attributes = determination_user_type_and_add_attributes(@the_user)

    @the_user.update(user_type: user_params[:user_type].to_i)
    @the_user = @the_user.reload
 
    add_to_new_table(@the_user, user_type_attributes, user_type)

    redirect_to the_users_path
  end

  def create
    @the_user = User.new(user_params.except(:user_type))
    @the_user.user_type = user_params[:user_type].to_i 
    if @the_user.save
      redirect_to the_users_path
    else
      render 'new'
    end
  end

  def destroy
    @the_user = User.find(params[:id])
    @the_user.destroy
    redirect_to the_users_path
  end

  private

    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation, :user_type)
    end

    def determination_user_type_and_add_attributes(the_user)
      if the_user.user_type == "client"
        client = Client.find_by(user_id: the_user.id)
        client_new = client.attributes.except("id")
        return client_new

      elsif the_user.user_type == "cleaner"
        cleaner = Cleaner.find_by(user_id: the_user.id)
        cleaner_new = cleaner.attributes.except("id", "start_date", "end_date")
        return cleaner_new 

      else
        admin = Admin.find_by(user_id: the_user.id)
        admin_new = admin.attributes.except("id")
        return admin_new
      end
    end
 
    def add_to_new_table(the_user, user_type_attributes, user_type)
      the_user_new = the_user.attributes
      encrypted_password = the_user.encrypted_password
  
      if user_type == "client" && the_user.user_type == "admin"
        the_user_create = delete_user_and_create(the_user, the_user_new, encrypted_password )
  
        admin_create = Admin.find_by(user_id: the_user_create.id)
        admin_create.update(user_type_attributes)
        
      elsif user_type == "client" && the_user.user_type == "cleaner"
        the_user_create = delete_user_and_create(the_user, the_user_new, encrypted_password)
     
        cleaner_create = Cleaner.find_by(user_id: the_user_create.id)
        cleaner_create.update(user_type_attributes)
        

      elsif user_type == "cleaner" && the_user.user_type == "client"
        the_user_create = delete_user_and_create(the_user, the_user_new, encrypted_password)
  
        client_create = Client.find_by(user_id: the_user_create.id)
        client_create.update(user_type_attributes)

      elsif user_type == "cleaner" && the_user.user_type == "admin"
        the_user_create = delete_user_and_create(the_user, the_user_new, encrypted_password)
  
        admin_create = Admin.find_by(user_id: the_user_create.id)
        admin_create.update(user_type_attributes)

      elsif user_type == "admin" && the_user.user_type == "client"
        the_user_create = delete_user_and_create(the_user, the_user_new, encrypted_password)
  
        client_create = Client.find_by(user_id: the_user_create.id)
        client_create.update(user_type_attributes)

      elsif user_type == "admin" && the_user.user_type == "cleaner"
        the_user_create = delete_user_and_create(the_user, the_user_new, encrypted_password)
  
        cleaner_create = Cleaner.find_by(user_id: the_user_create.id)
        cleaner_create.update(user_type_attributes)
      end
    end

    def delete_user_and_create(the_user, the_user_new, encrypted_password)
      the_user_create = User.new(the_user_new)
      the_user_create.password = "password"
      the_user_create.password_confirmation = "password"
      the_user_create.encrypted_password = encrypted_password
      the_user.destroy
      the_user_create.save!
      the_user_create
    end

    def user_admin
      redirect_to (root_path) unless current_user.user_type == "admin"
    end
end

app/views/the_users/edit.html.erb
<% provide(:title, "Editar usuario") %>
<% provide(:title_header, "Editar usuario") %>

<%= render 'shared/header_dinamic' %>

<div class="section">                                                           
  <div class="container" align="center">                                        
    <div class="columns is-centered">                                           
      <div class="column is-4"> 
        <%= form_for(@the_user, url: the_user_path(@the_user)) do |f| %>
  
          <div class="field">
            <%= f.label :user_type %>
            <%= f.select :user_type, [0,1,2] %>
          </div>

          <div class="actions">
            <%= f.submit "Actualizar usuario" %>
          </div>

        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/the_users/index.html.erb
<% provide(:title, "Usuarios") %>
<% provide(:title_header, "Usuarios") %>

<%= render 'shared/header_dinamic' %>

<div class="hero-body">
  <div class="container" align="center">
    <div class="table-container" style="width: 1010px; padding-left:50px">
      <div class="container" style="padding-left:150px">
        <%= form_tag(the_users_path, method: :get) do %>
          <div style = "width:200px; float:left">
            <%= text_field_tag :search_email, params[:search_email], placeholder:"filter by email", class:"input is-link is-small" %>
          </div>
          <%= submit_tag ("Search"), class: 'button is-link is-small'%>
        <% end %>
      </div>
      <br>
      <div style="width:500px"><%= paginate @the_users, window: 2 %></div>
      <br>

      <table class="table is-narrow is-hoverable -row-hover-background-color primary" >
        <thead>
          <tr>
            <th title="name">Nombre</th>
            <th title="phone">Telefono</th>
            <th title="email">Corre electronico</th>
            <th title="type">Clase</th>
            <th title="action">Acciones</th>
          </tr>
        </thead>
        <% @the_users.each do |u| %>
          <tbody>
            <tr>
              <% if u.user_type == "client" %>
                <% client = Client.find_by(user_id: u.id) %>
                <td><%= client.name %></td>
                <td><%= client.phone %></td>
              <% elsif u.user_type == "cleaner" %>
                <% cleaner = Cleaner.find_by(user_id: u.id) %>
                <td><%= cleaner.name %></td>
                <td><%= cleaner.phone %></td>
              <% else %>
                <% admin = Admin.find_by(user_id: u.id) %>
                <td><%= admin.name %></td>
                <td><%= admin.phone %></td>
              <% end %>
              <td><%= u.email %></td>
              <td><%= u.user_type %></td>
              <td>
                <% if u.user_type == "cleaner" %>
                  <% cleaner = Cleaner.find_by(user_id: u.id) %>
                  <%=  link_to 'Editar fechas', edit_date_cleaner_path(cleaner.id), class: "button is-small" %>
                <% end %>
                <%= link_to 'Editar', edit_the_user_path(u.id), class: "button is-small" %>
                <%= link_to 'Eliminar', the_user_path(u.id), method: :delete, data: { confirm: '¿Estas seguro?' } , class: "button is-small" %>
              </td>
            </tr>
          </tbody>
        <% end %>
      </table>
      <%= link_to "Registrar usuario", new_the_user_path, class: "button is-info is-rounded" %>
    </div>
  </div>
</div>

app/views/the_users/new.html.erb
<% provide(:title, "Registrar usuario") %>
<% provide(:title_header, "Registrar usuario") %>

<% render 'shared/header_dinamic' %>

<div class="section">                                                           
  <div class="container" align="center">                                        
    <div class="columns is-centered">                                           
      <div class="column is-4"> 
        <%= form_for(@the_user, url: the_users_path) do |f| %>
          <%= render "devise/shared/error_messages", resource: @the_user %>

          <div class="field">
            <%= f.label :email %><br />
            <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
          </div>

          <div class="field">
            <%= f.label :password %>
            <%= f.password_field :password, autocomplete: "new-password" %>
          </div>
 
          <div class="field">
            <%= f.label :password_confirmation %>
            <%= f.password_field :password_confirmation, autocomplete: "new-password" %>
          </div>

          <div class="field">
            <%= f.label :user_type %>
            <%= f.select :user_type, [ 0, 1, 2 ] %>
          </div>

          <div class="actions">
            <%= f.submit "Registrar usuario", class: "button is-info is-medium" %>
          </div>

        <% end %>
      </div>
    </div>
  </div>
</div>