config/routes.rb
Rails.application.routes.draw do
  get 'date_cleaner/edit'
  get 'cancel_service/cancel'
  patch 'orders/:id', to: 'orders#update', as: :update_order

  root 'home#index'

  devise_for :users 

  resources :the_users
  resources :date_cleaner, only: [:update, :edit]
  resources :clients,      only: [:edit, :update]
  resources :addresses
  resources :orders
  resources :services
  resources :cleaners,     only: [:edit, :update]
  resources :admins,       only: [:edit, :update]
  get '*path' => redirect('/')
end

app/controllers/date_cleaner_controller.rb
class DateCleanerController < ApplicationController
  before_action :user_admin
  before_action :authenticate_information

  def edit
    @cleaner = Cleaner.find(params[:id])
  end

  def update
    @cleaner = Cleaner.find(params[:id])
    @cleaner.update(date_cleaner_params)
    redirect_to the_users_path
  end

  private

    def date_cleaner_params
      params.require(:cleaner).permit(:start_date, :end_date)
    end

    def user_admin
      redirect_to (root_path) unless current_user.user_type == "admin"
    end    
end

app/helpers/date_cleaner_helper.rb
module DateCleanerHelper
end

app/views/date_cleaner/edit.html.erb
<% provide(:title, "Asignar fechas") %>
<% provide(:title_header, "Asignar fechas") %>

<%= render 'shared/header_dinamic' %>

<div class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-4">
        <%= form_for(@cleaner, url: date_cleaner_path(@cleaner)) do |f| %>
          
        <div class="field">
          <%= f.label :start_date %>
          <%= f.date_field :start_date, min: Date.today %>
        </div>

        <div class="field">
          <%= f.label :end_date %>
          <%= f.date_field :end_date, min: Date.tomorrow + 30.days %>
        </div>

        <div class="actions">
          <%= f.submit "Asignar fechas" %>
        </div>

      <% end %>
    </div>
  </div>
</div>